layout_spectrum: 0.7927421135827899
typography_spectrum: 0.14691893476992846
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.034632270224392414
  lightness: 0.2785624514799565
  saturation: 0.251507357461378
  rhythmicContrast: 0.5380054679699242
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: roboto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: eileen.is
purpose: []
