typography_spectrum: 0.83348
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#999084'
    - '#5a564d'
    - '#373628'
  brandStrength: 0.8574813751038164
  lightness: 0.26686259428970516
  saturation: 0.739050715463236
  rhythmicContrast: 0.040150148794054985
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21145
analytics:
  google: null
  facebook: null
  twitter: null
name: roboto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: eileen.is
purpose: []
